name: Test 7E3 Model Evaluation

on:
  workflow_dispatch:

jobs:
  test-report:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - id: qualification-environment
        name: Setup Qualification Environment
        uses: pchelle/osp-actions/setup-qualification-environment@showtext
        with:
          tools-path: tools.csv

      - id: evaluate-model
        name: Run evaluation
        uses: pchelle/osp-actions/report-evaluation@showtext
        with:
          model-repo: 7E3-Model
          model-version: '1.0'
          snapshot: '7E3'
          pk-sim-version: ${{ steps.qualification-environment.outputs.pk-sim-version }}
          qualification-framework-version: ${{ steps.qualification-environment.outputs.qualification-framework-version }}
          save-model-file: FALSE
          save-pdf: FALSE
          save-artifact: TRUE
      
